package dev.redstudio.netherite.item.laptop;

import com.mojang.blaze3d.matrix.MatrixStack;
import com.mojang.blaze3d.vertex.IVertexBuilder;
import net.minecraft.client.renderer.entity.model.EntityModel;
import net.minecraft.client.renderer.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class LaptopModel extends EntityModel<Entity> {
    //fields
    ModelRenderer Keyboard1;
    ModelRenderer Keyboard2;
    ModelRenderer KeyboardButton1;
    ModelRenderer KeyboardButton2;
    ModelRenderer KeyboardButton3;
    ModelRenderer KeyboardButton4;
    ModelRenderer KeyboardButton5;
    ModelRenderer KeyboardButton6;
    ModelRenderer KeyboardButton7;
    ModelRenderer KeyboardButton8;
    ModelRenderer KeyboardButton9;
    ModelRenderer KeyboardButton10;
    ModelRenderer KeyboardButton11;
    ModelRenderer KeyboardButton12;
    ModelRenderer KeyboardButton13;
    ModelRenderer KeyboardButton14;
    ModelRenderer KeyboardButton15;
    ModelRenderer KeyboardButton16;
    ModelRenderer KeyboardButton17;
    ModelRenderer KeyboardButton18;
    ModelRenderer KeyboardButton19;
    ModelRenderer KeyboardButton20;
    ModelRenderer KeyboardButton21;
    ModelRenderer KeyboardButton22;
    ModelRenderer KeyboardButton23;
    ModelRenderer KeyboardButton24;
    ModelRenderer KeyboardButton25;
    ModelRenderer KeyboardButton26;
    ModelRenderer KeyboardButton27;
    ModelRenderer KeyboardButton28;
    ModelRenderer KeyboardButton29;
    ModelRenderer KeyboardButton30;
    ModelRenderer KeyboardButton31;
    ModelRenderer KeyboardButton32;
    ModelRenderer KeyboardButton33;
    ModelRenderer KeyboardButton34;
    ModelRenderer KeyboardButton35;
    ModelRenderer KeyboardButton36;
    ModelRenderer KeyboardButton37;
    ModelRenderer KeyboardButton38;
    ModelRenderer Monitor1;
    ModelRenderer Monitor2;
    ModelRenderer Monitor3;
    ModelRenderer Monitor4;
    ModelRenderer Monitor5;
    ModelRenderer Monitor6;
    ModelRenderer Monitor7;
    ModelRenderer Trackpad;

    public LaptopModel() {
        textureWidth = 512;
        textureHeight = 512;

        Keyboard1 = new ModelRenderer(this, 0, 0);
        Keyboard1.addBox(0F, 0F, 0F, 10, 1, 17);
        Keyboard1.setRotationPoint(-2F, 22F, -9F);
        Keyboard1.setTextureSize(64, 32);
        Keyboard1.mirror = true;
        setRotation(Keyboard1, 0F, 0F, 0F);
        Keyboard2 = new ModelRenderer(this, 0, 0);
        Keyboard2.addBox(0F, 0F, 0F, 10, 1, 17);
        Keyboard2.setRotationPoint(-1.9F, 21.55F, -9F);
        Keyboard2.setTextureSize(64, 32);
        Keyboard2.mirror = true;
        setRotation(Keyboard2, 0F, 0F, 0.0455438F);
        KeyboardButton1 = new ModelRenderer(this, 100, 0);
        KeyboardButton1.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton1.setRotationPoint(-0.5F, 21.5F, -8.5F);
        KeyboardButton1.setTextureSize(64, 32);
        KeyboardButton1.mirror = true;
        setRotation(KeyboardButton1, 0F, 0F, 0F);
        KeyboardButton2 = new ModelRenderer(this, 100, 0);
        KeyboardButton2.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton2.setRotationPoint(-0.5F, 21.5F, -6.5F);
        KeyboardButton2.setTextureSize(64, 32);
        KeyboardButton2.mirror = true;
        setRotation(KeyboardButton2, 0F, 0F, 0F);
        KeyboardButton3 = new ModelRenderer(this, 100, 0);
        KeyboardButton3.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton3.setRotationPoint(-0.5F, 21.5F, -5F);
        KeyboardButton3.setTextureSize(64, 32);
        KeyboardButton3.mirror = true;
        setRotation(KeyboardButton3, 0F, 0F, 0F);
        KeyboardButton4 = new ModelRenderer(this, 100, 0);
        KeyboardButton4.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton4.setRotationPoint(-0.5F, 21.5F, -3.5F);
        KeyboardButton4.setTextureSize(64, 32);
        KeyboardButton4.mirror = true;
        setRotation(KeyboardButton4, 0F, 0F, 0F);
        KeyboardButton5 = new ModelRenderer(this, 100, 0);
        KeyboardButton5.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton5.setRotationPoint(-0.5F, 21.5F, -2F);
        KeyboardButton5.setTextureSize(64, 32);
        KeyboardButton5.mirror = true;
        setRotation(KeyboardButton5, 0F, 0F, 0F);
        KeyboardButton6 = new ModelRenderer(this, 100, 0);
        KeyboardButton6.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton6.setRotationPoint(-0.5F, 21.5F, -0.5F);
        KeyboardButton6.setTextureSize(64, 32);
        KeyboardButton6.mirror = true;
        setRotation(KeyboardButton6, 0F, 0F, 0F);
        KeyboardButton7 = new ModelRenderer(this, 100, 0);
        KeyboardButton7.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton7.setRotationPoint(-0.5F, 21.5F, 1F);
        KeyboardButton7.setTextureSize(64, 32);
        KeyboardButton7.mirror = true;
        setRotation(KeyboardButton7, 0F, 0F, 0F);
        KeyboardButton8 = new ModelRenderer(this, 100, 0);
        KeyboardButton8.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton8.setRotationPoint(-0.5F, 21.5F, 2.5F);
        KeyboardButton8.setTextureSize(64, 32);
        KeyboardButton8.mirror = true;
        setRotation(KeyboardButton8, 0F, 0F, 0F);
        KeyboardButton9 = new ModelRenderer(this, 100, 0);
        KeyboardButton9.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton9.setRotationPoint(-0.5F, 21.5F, 6.5F);
        KeyboardButton9.setTextureSize(64, 32);
        KeyboardButton9.mirror = true;
        setRotation(KeyboardButton9, 0F, 0F, 0F);
        KeyboardButton10 = new ModelRenderer(this, 100, 0);
        KeyboardButton10.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton10.setRotationPoint(-0.5F, 21.5F, 5F);
        KeyboardButton10.setTextureSize(64, 32);
        KeyboardButton10.mirror = true;
        setRotation(KeyboardButton10, 0F, 0F, 0F);
        KeyboardButton11 = new ModelRenderer(this, 100, 0);
        KeyboardButton11.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton11.setRotationPoint(1.3F, 21.6F, -8.5F);
        KeyboardButton11.setTextureSize(64, 32);
        KeyboardButton11.mirror = true;
        setRotation(KeyboardButton11, 0F, 0F, 0F);
        KeyboardButton12 = new ModelRenderer(this, 100, 0);
        KeyboardButton12.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton12.setRotationPoint(1.3F, 21.6F, -7F);
        KeyboardButton12.setTextureSize(64, 32);
        KeyboardButton12.mirror = true;
        setRotation(KeyboardButton12, 0F, 0F, 0F);
        KeyboardButton13 = new ModelRenderer(this, 100, 0);
        KeyboardButton13.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton13.setRotationPoint(1.3F, 21.6F, -5.5F);
        KeyboardButton13.setTextureSize(64, 32);
        KeyboardButton13.mirror = true;
        setRotation(KeyboardButton13, 0F, 0F, 0F);
        KeyboardButton14 = new ModelRenderer(this, 100, 0);
        KeyboardButton14.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton14.setRotationPoint(1.3F, 21.6F, -4F);
        KeyboardButton14.setTextureSize(64, 32);
        KeyboardButton14.mirror = true;
        setRotation(KeyboardButton14, 0F, 0F, 0F);
        KeyboardButton15 = new ModelRenderer(this, 100, 0);
        KeyboardButton15.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton15.setRotationPoint(1.3F, 21.6F, -2.5F);
        KeyboardButton15.setTextureSize(64, 32);
        KeyboardButton15.mirror = true;
        setRotation(KeyboardButton15, 0F, 0F, 0F);
        KeyboardButton16 = new ModelRenderer(this, 100, 0);
        KeyboardButton16.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton16.setRotationPoint(1.3F, 21.6F, -1F);
        KeyboardButton16.setTextureSize(64, 32);
        KeyboardButton16.mirror = true;
        setRotation(KeyboardButton16, 0F, 0F, 0F);
        KeyboardButton17 = new ModelRenderer(this, 100, 0);
        KeyboardButton17.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton17.setRotationPoint(1.3F, 21.6F, 0.5F);
        KeyboardButton17.setTextureSize(64, 32);
        KeyboardButton17.mirror = true;
        setRotation(KeyboardButton17, 0F, 0F, 0F);
        KeyboardButton18 = new ModelRenderer(this, 100, 0);
        KeyboardButton18.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton18.setRotationPoint(1.3F, 21.6F, 2F);
        KeyboardButton18.setTextureSize(64, 32);
        KeyboardButton18.mirror = true;
        setRotation(KeyboardButton18, 0F, 0F, 0F);
        KeyboardButton19 = new ModelRenderer(this, 100, 0);
        KeyboardButton19.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton19.setRotationPoint(1.3F, 21.6F, 3.5F);
        KeyboardButton19.setTextureSize(64, 32);
        KeyboardButton19.mirror = true;
        setRotation(KeyboardButton19, 0F, 0F, 0F);
        KeyboardButton20 = new ModelRenderer(this, 100, 0);
        KeyboardButton20.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton20.setRotationPoint(1.3F, 21.6F, 5F);
        KeyboardButton20.setTextureSize(64, 32);
        KeyboardButton20.mirror = true;
        setRotation(KeyboardButton20, 0F, 0F, 0F);
        KeyboardButton21 = new ModelRenderer(this, 100, 0);
        KeyboardButton21.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton21.setRotationPoint(1.3F, 21.6F, 6.5F);
        KeyboardButton21.setTextureSize(64, 32);
        KeyboardButton21.mirror = true;
        setRotation(KeyboardButton21, 0F, 0F, 0F);
        KeyboardButton22 = new ModelRenderer(this, 100, 0);
        KeyboardButton22.addBox(0F, 0F, 0F, 1, 1, 2);
        KeyboardButton22.setRotationPoint(2.5F, 21.7F, -8.5F);
        KeyboardButton22.setTextureSize(64, 32);
        KeyboardButton22.mirror = true;
        setRotation(KeyboardButton22, 0F, 0F, 0F);
        KeyboardButton23 = new ModelRenderer(this, 100, 0);
        KeyboardButton23.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton23.setRotationPoint(2.5F, 21.7F, -6F);
        KeyboardButton23.setTextureSize(64, 32);
        KeyboardButton23.mirror = true;
        setRotation(KeyboardButton23, 0F, 0F, 0F);
        KeyboardButton24 = new ModelRenderer(this, 100, 0);
        KeyboardButton24.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton24.setRotationPoint(2.5F, 21.7F, -4.5F);
        KeyboardButton24.setTextureSize(64, 32);
        KeyboardButton24.mirror = true;
        setRotation(KeyboardButton24, 0F, 0F, 0F);
        KeyboardButton25 = new ModelRenderer(this, 100, 0);
        KeyboardButton25.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton25.setRotationPoint(2.5F, 21.7F, -3F);
        KeyboardButton25.setTextureSize(64, 32);
        KeyboardButton25.mirror = true;
        setRotation(KeyboardButton25, 0F, 0F, 0F);
        KeyboardButton26 = new ModelRenderer(this, 100, 0);
        KeyboardButton26.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton26.setRotationPoint(2.5F, 21.7F, -1.5F);
        KeyboardButton26.setTextureSize(64, 32);
        KeyboardButton26.mirror = true;
        setRotation(KeyboardButton26, 0F, 0F, 0F);
        KeyboardButton27 = new ModelRenderer(this, 100, 0);
        KeyboardButton27.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton27.setRotationPoint(2.5F, 21.7F, 0F);
        KeyboardButton27.setTextureSize(64, 32);
        KeyboardButton27.mirror = true;
        setRotation(KeyboardButton27, 0F, 0F, 0F);
        KeyboardButton28 = new ModelRenderer(this, 100, 0);
        KeyboardButton28.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton28.setRotationPoint(2.5F, 21.7F, 1.5F);
        KeyboardButton28.setTextureSize(64, 32);
        KeyboardButton28.mirror = true;
        setRotation(KeyboardButton28, 0F, 0F, 0F);
        KeyboardButton29 = new ModelRenderer(this, 100, 0);
        KeyboardButton29.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton29.setRotationPoint(2.5F, 21.7F, 3F);
        KeyboardButton29.setTextureSize(64, 32);
        KeyboardButton29.mirror = true;
        setRotation(KeyboardButton29, 0F, 0F, 0F);
        KeyboardButton30 = new ModelRenderer(this, 100, 0);
        KeyboardButton30.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton30.setRotationPoint(2.5F, 21.7F, 4.5F);
        KeyboardButton30.setTextureSize(64, 32);
        KeyboardButton30.mirror = true;
        setRotation(KeyboardButton30, 0F, 0F, 0F);
        KeyboardButton31 = new ModelRenderer(this, 100, 0);
        KeyboardButton31.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton31.setRotationPoint(2.5F, 21.7F, 6F);
        KeyboardButton31.setTextureSize(64, 32);
        KeyboardButton31.mirror = true;
        setRotation(KeyboardButton31, 0F, 0F, 0F);
        KeyboardButton32 = new ModelRenderer(this, 100, 0);
        KeyboardButton32.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton32.setRotationPoint(3.7F, 21.7F, -8.5F);
        KeyboardButton32.setTextureSize(64, 32);
        KeyboardButton32.mirror = true;
        setRotation(KeyboardButton32, 0F, 0F, 0F);
        KeyboardButton33 = new ModelRenderer(this, 100, 0);
        KeyboardButton33.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton33.setRotationPoint(3.7F, 21.7F, -7F);
        KeyboardButton33.setTextureSize(64, 32);
        KeyboardButton33.mirror = true;
        setRotation(KeyboardButton33, 0F, 0F, 0F);
        KeyboardButton34 = new ModelRenderer(this, 100, 0);
        KeyboardButton34.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton34.setRotationPoint(3.7F, 21.7F, -5.5F);
        KeyboardButton34.setTextureSize(64, 32);
        KeyboardButton34.mirror = true;
        setRotation(KeyboardButton34, 0F, 0F, 0F);
        KeyboardButton35 = new ModelRenderer(this, 100, 0);
        KeyboardButton35.addBox(0F, 0F, 0F, 1, 1, 6);
        KeyboardButton35.setRotationPoint(3.7F, 21.7F, -4F);
        KeyboardButton35.setTextureSize(64, 32);
        KeyboardButton35.mirror = true;
        setRotation(KeyboardButton35, 0F, 0F, 0F);
        KeyboardButton36 = new ModelRenderer(this, 100, 0);
        KeyboardButton36.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton36.setRotationPoint(3.7F, 21.7F, 2.5F);
        KeyboardButton36.setTextureSize(64, 32);
        KeyboardButton36.mirror = true;
        setRotation(KeyboardButton36, 0F, 0F, 0F);
        KeyboardButton37 = new ModelRenderer(this, 100, 0);
        KeyboardButton37.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton37.setRotationPoint(3.7F, 21.7F, 4F);
        KeyboardButton37.setTextureSize(64, 32);
        KeyboardButton37.mirror = true;
        setRotation(KeyboardButton37, 0F, 0F, 0F);
        KeyboardButton38 = new ModelRenderer(this, 100, 0);
        KeyboardButton38.addBox(0F, 0F, 0F, 1, 1, 2);
        KeyboardButton38.setRotationPoint(3.7F, 21.7F, 5.5F);
        KeyboardButton38.setTextureSize(64, 32);
        KeyboardButton38.mirror = true;
        setRotation(KeyboardButton38, 0F, 0F, 0F);
        Monitor1 = new ModelRenderer(this, 200, 0);
        Monitor1.addBox(0F, 0F, 0F, 1, 2, 15);
        Monitor1.setRotationPoint(-2.6F, 21F, -8F);
        Monitor1.setTextureSize(64, 32);
        Monitor1.mirror = true;
        setRotation(Monitor1, 0F, 0F, -0.1858931F);
        Monitor2 = new ModelRenderer(this, 200, 0);
        Monitor2.addBox(0.3F, 0F, 0F, 1, 1, 17);
        Monitor2.setRotationPoint(-2.9F, 20.4F, -9F);
        Monitor2.setTextureSize(64, 32);
        Monitor2.mirror = true;
        setRotation(Monitor2, 0F, 0F, -0.1396263F);
        Monitor3 = new ModelRenderer(this, 200, 0);
        Monitor3.addBox(0.3F, -8F, 0F, 1, 8, 1);
        Monitor3.setRotationPoint(-2.9F, 20.4F, -9F);
        Monitor3.setTextureSize(64, 32);
        Monitor3.mirror = true;
        setRotation(Monitor3, 0F, 0F, -0.1396263F);
        Monitor4 = new ModelRenderer(this, 200, 0);
        Monitor4.addBox(0.3F, -8F, 16F, 1, 8, 1);
        Monitor4.setRotationPoint(-2.9F, 20.4F, -9F);
        Monitor4.setTextureSize(64, 32);
        Monitor4.mirror = true;
        setRotation(Monitor4, 0F, 0F, -0.1396263F);
        Monitor5 = new ModelRenderer(this, 200, 0);
        Monitor5.addBox(0.3F, -9F, 0F, 1, 1, 17);
        Monitor5.setRotationPoint(-2.9F, 20.4F, -9F);
        Monitor5.setTextureSize(64, 32);
        Monitor5.mirror = true;
        setRotation(Monitor5, 0F, 0F, -0.1396263F);
        Monitor6 = new ModelRenderer(this, 200, 0);
        Monitor6.addBox(-0.2F, -8.5F, 0F, 1, 9, 16);
        Monitor6.setRotationPoint(-2.9F, 20.4F, -8.5F);
        Monitor6.setTextureSize(64, 32);
        Monitor6.mirror = true;
        setRotation(Monitor6, 0F, 0F, -0.1396263F);
        Monitor7 = new ModelRenderer(this, 200, 0);
        Monitor7.addBox(0.2F, -8F, 0F, 1, 8, 15);
        Monitor7.setRotationPoint(-2.9F, 20.4F, -8F);
        Monitor7.setTextureSize(64, 32);
        Monitor7.mirror = true;
        setRotation(Monitor7, 0F, 0F, -0.1396263F);
        Trackpad = new ModelRenderer(this, 100, 0);
        Trackpad.addBox(0F, 0F, 0F, 3, 1, 5);
        Trackpad.setRotationPoint(4.9F, 21.77F, -4.5F);
        Trackpad.setTextureSize(64, 32);
        Trackpad.mirror = true;
        setRotation(Trackpad, 0F, 0F, 0.0523599F);
    }

    @Override
    public void render(MatrixStack matrixStack, IVertexBuilder buffer, int packedLight, int packedOverlay, float red, float green, float blue, float alpha) {
        Keyboard1.render(matrixStack, buffer, packedLight, packedOverlay);
        Keyboard2.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton1.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton2.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton3.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton4.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton5.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton6.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton7.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton8.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton9.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton10.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton11.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton12.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton13.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton14.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton15.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton16.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton17.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton18.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton19.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton20.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton21.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton22.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton23.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton24.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton25.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton26.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton27.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton28.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton29.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton30.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton31.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton32.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton33.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton34.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton35.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton36.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton37.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton38.render(matrixStack, buffer, packedLight, packedOverlay);
        Monitor1.render(matrixStack, buffer, packedLight, packedOverlay);
        Monitor2.render(matrixStack, buffer, packedLight, packedOverlay);
        Monitor3.render(matrixStack, buffer, packedLight, packedOverlay);
        Monitor4.render(matrixStack, buffer, packedLight, packedOverlay);
        Monitor5.render(matrixStack, buffer, packedLight, packedOverlay);
        Monitor6.render(matrixStack, buffer, packedLight, packedOverlay);
        Monitor7.render(matrixStack, buffer, packedLight, packedOverlay);
        Trackpad.render(matrixStack, buffer, packedLight, packedOverlay);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    @Override
    public void setRotationAngles(Entity entity, float v, float v1, float v2, float v3, float v4) {

    }

}