package dev.redstudio.netherite.item.pc;


import com.mojang.blaze3d.matrix.MatrixStack;
import com.mojang.blaze3d.vertex.IVertexBuilder;
import net.minecraft.client.renderer.entity.model.EntityModel;
import net.minecraft.client.renderer.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class PCModel extends EntityModel<Entity> {
    //fields
    ModelRenderer Keyboard1;
    ModelRenderer Keyboard2;
    ModelRenderer KeyboardButton1;
    ModelRenderer KeyboardButton2;
    ModelRenderer KeyboardButton3;
    ModelRenderer KeyboardButton4;
    ModelRenderer KeyboardButton5;
    ModelRenderer KeyboardButton6;
    ModelRenderer KeyboardButton7;
    ModelRenderer KeyboardButton8;
    ModelRenderer KeyboardButton9;
    ModelRenderer KeyboardButton10;
    ModelRenderer KeyboardButton11;
    ModelRenderer KeyboardButton12;
    ModelRenderer KeyboardButton13;
    ModelRenderer KeyboardButton14;
    ModelRenderer KeyboardButton15;
    ModelRenderer KeyboardButton16;
    ModelRenderer KeyboardButton17;
    ModelRenderer KeyboardButton18;
    ModelRenderer KeyboardButton19;
    ModelRenderer KeyboardButton20;
    ModelRenderer KeyboardButton21;
    ModelRenderer KeyboardButton22;
    ModelRenderer KeyboardButton23;
    ModelRenderer KeyboardButton24;
    ModelRenderer KeyboardButton25;
    ModelRenderer KeyboardButton26;
    ModelRenderer KeyboardButton27;
    ModelRenderer KeyboardButton28;
    ModelRenderer KeyboardButton29;
    ModelRenderer KeyboardButton30;
    ModelRenderer KeyboardButton31;
    ModelRenderer KeyboardButton32;
    ModelRenderer KeyboardButton33;
    ModelRenderer KeyboardButton34;
    ModelRenderer KeyboardButton35;
    ModelRenderer KeyboardButton36;
    ModelRenderer KeyboardButton37;
    ModelRenderer KeyboardButton38;
    ModelRenderer Mouse1;
    ModelRenderer Mouse2;
    ModelRenderer Mouse3;
    ModelRenderer Mouse4;
    ModelRenderer Mouse5Wheel;
    ModelRenderer Monitor1;
    ModelRenderer Monitor2;
    ModelRenderer Monitor3;
    ModelRenderer Monitor4;
    ModelRenderer Monitor5Screen;
    ModelRenderer Monitor6;
    ModelRenderer Monitor7;
    ModelRenderer Monitor8;
    ModelRenderer Monitor9;
    ModelRenderer CompBlock1;
    ModelRenderer CompBlock2;
    ModelRenderer CompBlock3;
    ModelRenderer CompBlock4;
    ModelRenderer CompBlock5Ventillator;

    public PCModel() {
        textureWidth = 512;
        textureHeight = 512;

        Keyboard1 = new ModelRenderer(this, 0, 0);
        Keyboard1.addBox(0F, 0F, 0F, 6, 1, 17);
        Keyboard1.setRotationPoint(-1F, 22F, -9F);
        Keyboard1.setTextureSize(64, 32);
        Keyboard1.mirror = true;
        setRotation(Keyboard1, 0F, 0F, 0F);
        Keyboard2 = new ModelRenderer(this, 0, 0);
        Keyboard2.addBox(0F, 0F, 0F, 6, 1, 17);
        Keyboard2.setRotationPoint(-0.9F, 21F, -9F);
        Keyboard2.setTextureSize(64, 32);
        Keyboard2.mirror = true;
        setRotation(Keyboard2, 0F, 0F, 0.1570796F);
        KeyboardButton1 = new ModelRenderer(this, 100, 0);
        KeyboardButton1.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton1.setRotationPoint(-0.5F, 21F, -8.5F);
        KeyboardButton1.setTextureSize(64, 32);
        KeyboardButton1.mirror = true;
        setRotation(KeyboardButton1, 0F, 0F, 0F);
        KeyboardButton2 = new ModelRenderer(this, 100, 0);
        KeyboardButton2.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton2.setRotationPoint(-0.5F, 21F, -6.5F);
        KeyboardButton2.setTextureSize(64, 32);
        KeyboardButton2.mirror = true;
        setRotation(KeyboardButton2, 0F, 0F, 0F);
        KeyboardButton3 = new ModelRenderer(this, 100, 0);
        KeyboardButton3.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton3.setRotationPoint(-0.5F, 21F, -5F);
        KeyboardButton3.setTextureSize(64, 32);
        KeyboardButton3.mirror = true;
        setRotation(KeyboardButton3, 0F, 0F, 0F);
        KeyboardButton4 = new ModelRenderer(this, 100, 0);
        KeyboardButton4.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton4.setRotationPoint(-0.5F, 21F, -3.5F);
        KeyboardButton4.setTextureSize(64, 32);
        KeyboardButton4.mirror = true;
        setRotation(KeyboardButton4, 0F, 0F, 0F);
        KeyboardButton5 = new ModelRenderer(this, 100, 0);
        KeyboardButton5.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton5.setRotationPoint(-0.5F, 21F, -2F);
        KeyboardButton5.setTextureSize(64, 32);
        KeyboardButton5.mirror = true;
        setRotation(KeyboardButton5, 0F, 0F, 0F);
        KeyboardButton6 = new ModelRenderer(this, 100, 0);
        KeyboardButton6.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton6.setRotationPoint(-0.5F, 21F, -0.5F);
        KeyboardButton6.setTextureSize(64, 32);
        KeyboardButton6.mirror = true;
        setRotation(KeyboardButton6, 0F, 0F, 0F);
        KeyboardButton7 = new ModelRenderer(this, 100, 0);
        KeyboardButton7.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton7.setRotationPoint(-0.5F, 21F, 1F);
        KeyboardButton7.setTextureSize(64, 32);
        KeyboardButton7.mirror = true;
        setRotation(KeyboardButton7, 0F, 0F, 0F);
        KeyboardButton8 = new ModelRenderer(this, 100, 0);
        KeyboardButton8.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton8.setRotationPoint(-0.5F, 21F, 2.5F);
        KeyboardButton8.setTextureSize(64, 32);
        KeyboardButton8.mirror = true;
        setRotation(KeyboardButton8, 0F, 0F, 0F);
        KeyboardButton9 = new ModelRenderer(this, 100, 0);
        KeyboardButton9.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton9.setRotationPoint(-0.5F, 21F, 6.5F);
        KeyboardButton9.setTextureSize(64, 32);
        KeyboardButton9.mirror = true;
        setRotation(KeyboardButton9, 0F, 0F, 0F);
        KeyboardButton10 = new ModelRenderer(this, 100, 0);
        KeyboardButton10.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton10.setRotationPoint(-0.5F, 21F, 5F);
        KeyboardButton10.setTextureSize(64, 32);
        KeyboardButton10.mirror = true;
        setRotation(KeyboardButton10, 0F, 0F, 0F);
        KeyboardButton11 = new ModelRenderer(this, 100, 0);
        KeyboardButton11.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton11.setRotationPoint(1.3F, 21.2F, -8.5F);
        KeyboardButton11.setTextureSize(64, 32);
        KeyboardButton11.mirror = true;
        setRotation(KeyboardButton11, 0F, 0F, 0F);
        KeyboardButton12 = new ModelRenderer(this, 100, 0);
        KeyboardButton12.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton12.setRotationPoint(1.3F, 21.2F, -7F);
        KeyboardButton12.setTextureSize(64, 32);
        KeyboardButton12.mirror = true;
        setRotation(KeyboardButton12, 0F, 0F, 0F);
        KeyboardButton13 = new ModelRenderer(this, 100, 0);
        KeyboardButton13.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton13.setRotationPoint(1.3F, 21.2F, -5.5F);
        KeyboardButton13.setTextureSize(64, 32);
        KeyboardButton13.mirror = true;
        setRotation(KeyboardButton13, 0F, 0F, 0F);
        KeyboardButton14 = new ModelRenderer(this, 100, 0);
        KeyboardButton14.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton14.setRotationPoint(1.3F, 21.2F, -4F);
        KeyboardButton14.setTextureSize(64, 32);
        KeyboardButton14.mirror = true;
        setRotation(KeyboardButton14, 0F, 0F, 0F);
        KeyboardButton15 = new ModelRenderer(this, 100, 0);
        KeyboardButton15.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton15.setRotationPoint(1.3F, 21.2F, -2.5F);
        KeyboardButton15.setTextureSize(64, 32);
        KeyboardButton15.mirror = true;
        setRotation(KeyboardButton15, 0F, 0F, 0F);
        KeyboardButton16 = new ModelRenderer(this, 100, 0);
        KeyboardButton16.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton16.setRotationPoint(1.3F, 21.2F, -1F);
        KeyboardButton16.setTextureSize(64, 32);
        KeyboardButton16.mirror = true;
        setRotation(KeyboardButton16, 0F, 0F, 0F);
        KeyboardButton17 = new ModelRenderer(this, 100, 0);
        KeyboardButton17.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton17.setRotationPoint(1.3F, 21.2F, 0.5F);
        KeyboardButton17.setTextureSize(64, 32);
        KeyboardButton17.mirror = true;
        setRotation(KeyboardButton17, 0F, 0F, 0F);
        KeyboardButton18 = new ModelRenderer(this, 100, 0);
        KeyboardButton18.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton18.setRotationPoint(1.3F, 21.2F, 2F);
        KeyboardButton18.setTextureSize(64, 32);
        KeyboardButton18.mirror = true;
        setRotation(KeyboardButton18, 0F, 0F, 0F);
        KeyboardButton19 = new ModelRenderer(this, 100, 0);
        KeyboardButton19.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton19.setRotationPoint(1.3F, 21.2F, 3.5F);
        KeyboardButton19.setTextureSize(64, 32);
        KeyboardButton19.mirror = true;
        setRotation(KeyboardButton19, 0F, 0F, 0F);
        KeyboardButton20 = new ModelRenderer(this, 100, 0);
        KeyboardButton20.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton20.setRotationPoint(1.3F, 21.2F, 5F);
        KeyboardButton20.setTextureSize(64, 32);
        KeyboardButton20.mirror = true;
        setRotation(KeyboardButton20, 0F, 0F, 0F);
        KeyboardButton21 = new ModelRenderer(this, 100, 0);
        KeyboardButton21.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton21.setRotationPoint(1.3F, 21.2F, 6.5F);
        KeyboardButton21.setTextureSize(64, 32);
        KeyboardButton21.mirror = true;
        setRotation(KeyboardButton21, 0F, 0F, 0F);
        KeyboardButton22 = new ModelRenderer(this, 100, 0);
        KeyboardButton22.addBox(0F, 0F, 0F, 1, 1, 2);
        KeyboardButton22.setRotationPoint(2.5F, 21.4F, -8.5F);
        KeyboardButton22.setTextureSize(64, 32);
        KeyboardButton22.mirror = true;
        setRotation(KeyboardButton22, 0F, 0F, 0F);
        KeyboardButton23 = new ModelRenderer(this, 100, 0);
        KeyboardButton23.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton23.setRotationPoint(2.5F, 21.4F, -6F);
        KeyboardButton23.setTextureSize(64, 32);
        KeyboardButton23.mirror = true;
        setRotation(KeyboardButton23, 0F, 0F, 0F);
        KeyboardButton24 = new ModelRenderer(this, 100, 0);
        KeyboardButton24.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton24.setRotationPoint(2.5F, 21.4F, -4.5F);
        KeyboardButton24.setTextureSize(64, 32);
        KeyboardButton24.mirror = true;
        setRotation(KeyboardButton24, 0F, 0F, 0F);
        KeyboardButton25 = new ModelRenderer(this, 100, 0);
        KeyboardButton25.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton25.setRotationPoint(2.5F, 21.4F, -3F);
        KeyboardButton25.setTextureSize(64, 32);
        KeyboardButton25.mirror = true;
        setRotation(KeyboardButton25, 0F, 0F, 0F);
        KeyboardButton26 = new ModelRenderer(this, 100, 0);
        KeyboardButton26.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton26.setRotationPoint(2.5F, 21.4F, -1.5F);
        KeyboardButton26.setTextureSize(64, 32);
        KeyboardButton26.mirror = true;
        setRotation(KeyboardButton26, 0F, 0F, 0F);
        KeyboardButton27 = new ModelRenderer(this, 100, 0);
        KeyboardButton27.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton27.setRotationPoint(2.5F, 21.4F, 0F);
        KeyboardButton27.setTextureSize(64, 32);
        KeyboardButton27.mirror = true;
        setRotation(KeyboardButton27, 0F, 0F, 0F);
        KeyboardButton28 = new ModelRenderer(this, 100, 0);
        KeyboardButton28.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton28.setRotationPoint(2.5F, 21.4F, 1.5F);
        KeyboardButton28.setTextureSize(64, 32);
        KeyboardButton28.mirror = true;
        setRotation(KeyboardButton28, 0F, 0F, 0F);
        KeyboardButton29 = new ModelRenderer(this, 100, 0);
        KeyboardButton29.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton29.setRotationPoint(2.5F, 21.4F, 3F);
        KeyboardButton29.setTextureSize(64, 32);
        KeyboardButton29.mirror = true;
        setRotation(KeyboardButton29, 0F, 0F, 0F);
        KeyboardButton30 = new ModelRenderer(this, 100, 0);
        KeyboardButton30.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton30.setRotationPoint(2.5F, 21.4F, 4.5F);
        KeyboardButton30.setTextureSize(64, 32);
        KeyboardButton30.mirror = true;
        setRotation(KeyboardButton30, 0F, 0F, 0F);
        KeyboardButton31 = new ModelRenderer(this, 100, 0);
        KeyboardButton31.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton31.setRotationPoint(2.5F, 21.4F, 6F);
        KeyboardButton31.setTextureSize(64, 32);
        KeyboardButton31.mirror = true;
        setRotation(KeyboardButton31, 0F, 0F, 0F);
        KeyboardButton32 = new ModelRenderer(this, 100, 0);
        KeyboardButton32.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton32.setRotationPoint(3.7F, 21.6F, -8.5F);
        KeyboardButton32.setTextureSize(64, 32);
        KeyboardButton32.mirror = true;
        setRotation(KeyboardButton32, 0F, 0F, 0F);
        KeyboardButton33 = new ModelRenderer(this, 100, 0);
        KeyboardButton33.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton33.setRotationPoint(3.7F, 21.6F, -7F);
        KeyboardButton33.setTextureSize(64, 32);
        KeyboardButton33.mirror = true;
        setRotation(KeyboardButton33, 0F, 0F, 0F);
        KeyboardButton34 = new ModelRenderer(this, 100, 0);
        KeyboardButton34.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton34.setRotationPoint(3.7F, 21.6F, -5.5F);
        KeyboardButton34.setTextureSize(64, 32);
        KeyboardButton34.mirror = true;
        setRotation(KeyboardButton34, 0F, 0F, 0F);
        KeyboardButton35 = new ModelRenderer(this, 100, 0);
        KeyboardButton35.addBox(0F, 0F, 0F, 1, 1, 6);
        KeyboardButton35.setRotationPoint(3.7F, 21.6F, -4F);
        KeyboardButton35.setTextureSize(64, 32);
        KeyboardButton35.mirror = true;
        setRotation(KeyboardButton35, 0F, 0F, 0F);
        KeyboardButton36 = new ModelRenderer(this, 100, 0);
        KeyboardButton36.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton36.setRotationPoint(3.7F, 21.6F, 2.5F);
        KeyboardButton36.setTextureSize(64, 32);
        KeyboardButton36.mirror = true;
        setRotation(KeyboardButton36, 0F, 0F, 0F);
        KeyboardButton37 = new ModelRenderer(this, 100, 0);
        KeyboardButton37.addBox(0F, 0F, 0F, 1, 1, 1);
        KeyboardButton37.setRotationPoint(3.7F, 21.6F, 4F);
        KeyboardButton37.setTextureSize(64, 32);
        KeyboardButton37.mirror = true;
        setRotation(KeyboardButton37, 0F, 0F, 0F);
        KeyboardButton38 = new ModelRenderer(this, 100, 0);
        KeyboardButton38.addBox(0F, 0F, 0F, 1, 1, 2);
        KeyboardButton38.setRotationPoint(3.7F, 21.6F, 5.5F);
        KeyboardButton38.setTextureSize(64, 32);
        KeyboardButton38.mirror = true;
        setRotation(KeyboardButton38, 0F, 0F, 0F);
        Mouse1 = new ModelRenderer(this, 150, 0);
        Mouse1.addBox(0F, 0F, 0F, 4, 1, 3);
        Mouse1.setRotationPoint(0F, 22F, 10.5F);
        Mouse1.setTextureSize(64, 32);
        Mouse1.mirror = true;
        setRotation(Mouse1, 0F, 0F, 0F);
        Mouse2 = new ModelRenderer(this, 150, 0);
        Mouse2.addBox(0F, 0F, 0F, 3, 1, 3);
        Mouse2.setRotationPoint(1F, 21.8F, 10.5F);
        Mouse2.setTextureSize(64, 32);
        Mouse2.mirror = true;
        setRotation(Mouse2, 0F, 0F, 0F);
        Mouse3 = new ModelRenderer(this, 150, 0);
        Mouse3.addBox(0F, 0F, 0F, 1, 1, 1);
        Mouse3.setRotationPoint(-0.1F, 21.8F, 10.5F);
        Mouse3.setTextureSize(64, 32);
        Mouse3.mirror = true;
        setRotation(Mouse3, 0F, 0F, 0F);
        Mouse4 = new ModelRenderer(this, 150, 0);
        Mouse4.addBox(0F, 0F, 0F, 1, 1, 1);
        Mouse4.setRotationPoint(-0.1F, 21.8F, 12.5F);
        Mouse4.setTextureSize(64, 32);
        Mouse4.mirror = true;
        setRotation(Mouse4, 0F, 0F, 0F);
        Mouse5Wheel = new ModelRenderer(this, 150, 30);
        Mouse5Wheel.addBox(0F, 0F, 0F, 1, 1, 1);
        Mouse5Wheel.setRotationPoint(-0.1F, 21.6F, 11.5F);
        Mouse5Wheel.setTextureSize(64, 32);
        Mouse5Wheel.mirror = true;
        setRotation(Mouse5Wheel, 0F, 0F, 0F);
        Monitor1 = new ModelRenderer(this, 200, 0);
        Monitor1.addBox(0F, 0F, 0F, 6, 1, 9);
        Monitor1.setRotationPoint(-8F, 22F, -5F);
        Monitor1.setTextureSize(64, 32);
        Monitor1.mirror = true;
        setRotation(Monitor1, 0F, 0F, 0F);
        Monitor2 = new ModelRenderer(this, 200, 0);
        Monitor2.addBox(0F, 0F, 0F, 1, 7, 3);
        Monitor2.setRotationPoint(-6F, 15F, -2F);
        Monitor2.setTextureSize(64, 32);
        Monitor2.mirror = true;
        setRotation(Monitor2, 0F, 0F, 0F);
        Monitor3 = new ModelRenderer(this, 200, 0);
        Monitor3.addBox(0F, 0F, 0F, 1, 14, 19);
        Monitor3.setRotationPoint(-7F, 4F, -10F);
        Monitor3.setTextureSize(64, 32);
        Monitor3.mirror = true;
        setRotation(Monitor3, 0F, 0F, -0.1396263F);
        Monitor4 = new ModelRenderer(this, 200, 0);
        Monitor4.addBox(-0.5F, 0.5F, 0.5F, 1, 13, 18);
        Monitor4.setRotationPoint(-7F, 4F, -10F);
        Monitor4.setTextureSize(64, 32);
        Monitor4.mirror = true;
        setRotation(Monitor4, 0F, 0F, -0.1396263F);
        Monitor5Screen = new ModelRenderer(this, 200, 40);
        Monitor5Screen.addBox(0.1F, 0.5F, -0.5F, 1, 13, 18);
        Monitor5Screen.setRotationPoint(-7F, 4F, -9F);
        Monitor5Screen.setTextureSize(64, 32);
        Monitor5Screen.mirror = true;
        setRotation(Monitor5Screen, 0F, 0F, -0.1396263F);
        Monitor6 = new ModelRenderer(this, 200, 0);
        Monitor6.addBox(0.3F, 0F, 0F, 1, 14, 1);
        Monitor6.setRotationPoint(-7F, 4F, 8F);
        Monitor6.setTextureSize(64, 32);
        Monitor6.mirror = true;
        setRotation(Monitor6, 0F, 0F, -0.1396263F);
        Monitor7 = new ModelRenderer(this, 200, 0);
        Monitor7.addBox(0.3F, 0F, 0F, 1, 14, 1);
        Monitor7.setRotationPoint(-7F, 4F, -10F);
        Monitor7.setTextureSize(64, 32);
        Monitor7.mirror = true;
        setRotation(Monitor7, 0F, 0F, -0.1396263F);
        Monitor8 = new ModelRenderer(this, 200, 0);
        Monitor8.addBox(0.3F, 0F, 0F, 1, 1, 17);
        Monitor8.setRotationPoint(-7F, 4F, -9F);
        Monitor8.setTextureSize(64, 32);
        Monitor8.mirror = true;
        setRotation(Monitor8, 0F, 0F, -0.1396263F);
        Monitor9 = new ModelRenderer(this, 200, 0);
        Monitor9.addBox(0.3F, 13F, 0F, 1, 1, 17);
        Monitor9.setRotationPoint(-7F, 4F, -9F);
        Monitor9.setTextureSize(64, 32);
        Monitor9.mirror = true;
        setRotation(Monitor9, 0F, 0F, -0.1396263F);
        CompBlock1 = new ModelRenderer(this, 0, 100);
        CompBlock1.addBox(0F, 0F, 0F, 19, 19, 8);
        CompBlock1.setRotationPoint(-10F, 4F, 19F);
        CompBlock1.setTextureSize(64, 32);
        CompBlock1.mirror = true;
        setRotation(CompBlock1, 0F, 0F, 0F);
        CompBlock2 = new ModelRenderer(this, 130, 100);
        CompBlock2.addBox(0F, 0F, 0F, 1, 2, 2);
        CompBlock2.setRotationPoint(8.2F, 17F, 22F);
        CompBlock2.setTextureSize(64, 32);
        CompBlock2.mirror = true;
        setRotation(CompBlock2, 0F, 0F, 0F);
        CompBlock3 = new ModelRenderer(this, 100, 100);
        CompBlock3.addBox(0F, 0F, 0F, 1, 1, 7);
        CompBlock3.setRotationPoint(8.1F, 5F, 19.5F);
        CompBlock3.setTextureSize(64, 32);
        CompBlock3.mirror = true;
        setRotation(CompBlock3, 0F, 0F, 0F);
        CompBlock4 = new ModelRenderer(this, 0, 100);
        CompBlock4.addBox(0F, 0F, 0F, 1, 17, 7);
        CompBlock4.setRotationPoint(-10.5F, 5F, 19.5F);
        CompBlock4.setTextureSize(64, 32);
        CompBlock4.mirror = true;
        setRotation(CompBlock4, 0F, 0F, 0F);
        CompBlock5Ventillator = new ModelRenderer(this, 160, 100);
        CompBlock5Ventillator.addBox(0F, 0F, 0F, 5, 5, 1);
        CompBlock5Ventillator.setRotationPoint(-6F, 10F, 18.4F);
        CompBlock5Ventillator.setTextureSize(64, 32);
        CompBlock5Ventillator.mirror = true;
        setRotation(CompBlock5Ventillator, 0F, 0F, 0F);
    }

    @Override
    public void setRotationAngles(Entity entity, float v, float v1, float v2, float v3, float v4) {
        
    }

    @Override
    public void render(MatrixStack matrixStack, IVertexBuilder buffer, int packedLight, int packedOverlay, float red, float green, float blue, float alpha) {
        Keyboard2.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton1.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton2.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton3.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton4.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton5.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton6.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton7.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton8.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton9.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton10.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton11.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton12.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton13.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton14.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton15.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton16.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton17.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton18.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton19.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton20.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton21.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton22.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton23.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton24.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton25.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton26.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton27.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton28.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton29.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton30.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton31.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton32.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton33.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton34.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton35.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton36.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton37.render(matrixStack, buffer, packedLight, packedOverlay);
        KeyboardButton38.render(matrixStack, buffer, packedLight, packedOverlay);
        Mouse1.render(matrixStack, buffer, packedLight, packedOverlay);
        Mouse2.render(matrixStack, buffer, packedLight, packedOverlay);
        Mouse3.render(matrixStack, buffer, packedLight, packedOverlay);
        Mouse4.render(matrixStack, buffer, packedLight, packedOverlay);
        Mouse5Wheel.render(matrixStack, buffer, packedLight, packedOverlay);
        Monitor1.render(matrixStack, buffer, packedLight, packedOverlay);
        Monitor2.render(matrixStack, buffer, packedLight, packedOverlay);
        Monitor3.render(matrixStack, buffer, packedLight, packedOverlay);
        Monitor4.render(matrixStack, buffer, packedLight, packedOverlay);
        Monitor5Screen.render(matrixStack, buffer, packedLight, packedOverlay);
        Monitor6.render(matrixStack, buffer, packedLight, packedOverlay);
        Monitor7.render(matrixStack, buffer, packedLight, packedOverlay);
        Monitor8.render(matrixStack, buffer, packedLight, packedOverlay);
        Monitor9.render(matrixStack, buffer, packedLight, packedOverlay);
        CompBlock1.render(matrixStack, buffer, packedLight, packedOverlay);
        CompBlock2.render(matrixStack, buffer, packedLight, packedOverlay);
        CompBlock3.render(matrixStack, buffer, packedLight, packedOverlay);
        CompBlock4.render(matrixStack, buffer, packedLight, packedOverlay);
        CompBlock5Ventillator.render(matrixStack, buffer, packedLight, packedOverlay);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }
    
}
